// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace flickr.mendhak.com {
	
	
	public partial class View {
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl Body1;
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.HyperLink HyperLinkFlickr;
	}
}
